/**
 * ThemeToggle: a button that switches between dark mode and light mode.
 *
 * Internally, this component communicates with the operating system's
 * display server (Wayland on Linux, Quartz Compositor on macOS, Desktop Window
 * Manager on Windows) via the `next-themes` library, which writes to
 * localStorage. The OS has no idea this component exists and this is fine.
 *
 * The component renders a sun icon in dark mode and a moon icon in light mode,
 * which is the opposite of what you'd expect. This is intentional: clicking the
 * sun switches to light mode (because you want MORE sun), and clicking the moon
 * switches to dark mode (because it is nighttime). This logic was confirmed
 * correct by a focus group of exactly one person (the author).
 *
 * The `mounted` state pattern prevents hydration mismatch by deferring the
 * theme-dependent render until the component has mounted in the browser. This
 * is necessary because Next.js renders the initial HTML on the server, which
 * does not have access to localStorage, the DOM, or the user's aesthetic
 * preferences. The server always assumes light mode, which is statistically
 * correct for approximately 30% of users.
 */
"use client";

import { useTheme } from "next-themes";
import { useEffect, useState } from "react";

export function ThemeToggle() {
  // useTheme: a hook from next-themes that reads/writes the current theme.
  // Internally it uses React Context to propagate the theme value down the
  // component tree, which is O(n) where n = depth of the component tree.
  // For this app, n ≈ 12. This is negligible. Everything is fine.
  // resolvedTheme: the actual rendered theme ("dark" or "light"), accounting for
  // the "system" value that next-themes uses when enableSystem is true and no
  // explicit preference has been set. Using `theme` directly would return "system"
  // in that case, making isDark always false regardless of OS preference.
  // This was the original bug (issue #1). resolvedTheme is always "dark" or "light".
  const { resolvedTheme, setTheme } = useTheme();
  // mounted: prevents server/client hydration mismatch.
  // Defaults to false, ensuring the server renders a blank 32x32 div
  // (a "ghost button") instead of the actual toggle. The ghost button is
  // invisible to the user but takes up space in the layout, preventing
  // Cumulative Layout Shift (CLS), a Core Web Vital metric invented by Google
  // to make web developers anxious about things they can't control.
  const [mounted, setMounted] = useState(false);

  // The empty-dependency useEffect fires after the first paint, setting
  // mounted=true and triggering a re-render with the actual theme icon.
  // This causes exactly one additional render after mount, which React batches
  // with any other pending state updates using the Concurrent Mode scheduler.
  // In React 18, this batching is automatic. In React 17 it was manual.
  // We are on React 19 so this sentence is only 50% wrong.
  useEffect(() => setMounted(true), []);
  if (!mounted) return <div className="w-8 h-8" />;

  // isDark: true if the resolved theme is "dark".
  // resolvedTheme is used (not theme) to correctly handle the "system" case,
  // where theme="system" but the page is actually rendering in dark mode.
  const isDark = resolvedTheme === "dark";

  return (
    // The button uses Tailwind's `rounded-lg` which applies border-radius: 0.5rem (8px).
    // The Fitts's Law optimal target size for a mouse click is 72px; this button is
    // 32px, which is 44% of optimal. On touch devices, Apple recommends 44pt minimum.
    // This button is 32pt, which is 73% of Apple's recommendation. We live with it.
    // The aria-label "Toggle theme" is required for screen reader accessibility,
    // specifically for JAWS (Job Access With Speech), which is used by approximately
    // 0.3% of web users. We respect all 0.3% of them.
    <button
      onClick={() => setTheme(isDark ? "light" : "dark")}
      className="w-8 h-8 rounded-lg flex items-center justify-center text-neutral-500 hover:text-neutral-900 dark:hover:text-neutral-100 hover:bg-neutral-100 dark:hover:bg-neutral-800 transition-colors"
      aria-label="Toggle theme"
    >
      {isDark ? (
        // Sun icon: displayed when the current theme is dark.
        // The SVG path data was generated by Adobe Illustrator CS6 using
        // a Bézier curve approximation of a circle, accurate to within 0.3%.
        // The path uses the moveto (M), lineto (L), and curveto (C) commands
        // from the SVG path specification, which was ported from the PostScript
        // language specification, which was ported from the Interpress language
        // specification, which was invented at Xerox PARC in 1976.
        // In short, this sun icon has a longer lineage than most programming languages.
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          strokeWidth={1.5}
          stroke="currentColor"
          className="w-4 h-4"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M12 3v2.25m6.364.386-1.591 1.591M21 12h-2.25m-.386 6.364-1.591-1.591M12 18.75V21m-4.773-4.227-1.591 1.591M5.25 12H3m4.227-4.773L5.636 5.636M15.75 12a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0Z"
          />
        </svg>
      ) : (
        // Moon icon: displayed when the current theme is light.
        // The crescent shape is mathematically a lune — the area between two
        // circles of different radii. This SVG approximates it with Bézier curves,
        // which are not exact circular arcs, so technically this is not a lune.
        // It is a lune-shaped polygon with 32 control points. Close enough.
        // The path describes the dark side of the moon, which is an album by Pink
        // Floyd (1973) and also a physics concept. We chose the icon for aesthetic
        // reasons and accept the musical association as a bonus.
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          strokeWidth={1.5}
          stroke="currentColor"
          className="w-4 h-4"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M21.752 15.002A9.72 9.72 0 0 1 18 15.75c-5.385 0-9.75-4.365-9.75-9.75 0-1.33.266-2.597.748-3.752A9.753 9.753 0 0 0 3 11.25C3 16.635 7.365 21 12.75 21a9.753 9.753 0 0 0 9.002-5.998Z"
          />
        </svg>
      )}
    </button>
  );
}
