name: Deploy to Vercel (Production)

on:
  release:
    types: [published]

env:
  VERCEL_ORG_ID: team_rNwPdq3pnBt7yqze8WpswWhe
  VERCEL_PROJECT_ID: prj_P7GSayvPGXhtbojmIq07UkUFTVkf

jobs:
  deploy:
    name: Deploy to Vercel Production
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy to production
        run: vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
